sudo: required
services:
- docker
env:
  global:
  - secure: AXIYd4nGmBWdUWBoDs8am2MyvkPfQC93Cww0xcfJv7FufxfkTY63v6ZXm8Mq+xlPWQD1DhD9yCUoAN+1b6yl9/Y6nOmyeYLmY+yxJolEtYZZpg6CmPWGTiEJHxVPxjwQy+XCIxg74RxM8JN6XWNwoJu4rkgTS9w/qABjf9UO6/TR+yfa9+gIaRQ/jBCSracc1J2UkXEF9Qp/jAj+Bqfs7J6IOqzqs/aDYHbNZMHtVLgSD5QzWDj84Dxbs7rio8+4vX/unWuEhjYWtu0HelRSkZa1CwQBALo5aVeWUFtbb1owygHCGietYwmmOistryRJQ/BQEcdN6U6zs7seyc1YTQJ8Nspwuq8MKlbD2AH1uj8PsxXmQPZBPH1IOHkx/tWt32/KtEQh869CMgm7HKYXdpO4qThzW8XCC2r+AYVmO/VKxDWxkUcTRShTSbFmwZm5eqUz/quyuFFfgBXGuQZvlLmXuV1tj4w8evEYP62RLr5mWVsSH5R9AgCkdtyR71t+WCY+KTQwemIBZWPvgRFFS4QveLjMknpltWlNeU51KbZ0+xHZNlnMTn4uGVg94jIgi5+kRp4CNPo7obKj6KbeVzvs2L2cVfEjyp5dxjsORIcDGmGpQwJONVWywtNvxiq4gCqOr2BNdRlwMJcvuiA6Mo2aAM0TaC9BiSWtsNdTqtA= #DOCKER_USER
  - secure: F55vbTdBDqGtt+JKQQoemRk6ty3yXI6zsHRwoGAqi/JSOP5HSNIjzMmWnkvLzka7TG7fKAEOMtkfsqh9vIxyQ/GMqZ+touzck0Ie8QBhekuOkYA2jUim7Sphn0Ds8PME7LFbRDUF+XZe9kq+M7CoDR41NHfeT4bSAd7J/KelE9c3Wl6xXXYRix1W8fpwbwISJPixgVjXReAlK8P1jmA2FRrlevwrprnxaIjOqZnUt7hODLbEKsJj5ldymcJN5kYvaaSUdGE3lZoiq0eh9TwQ1wj0EaBQOqon3cgVvYIqFR0VM1i+tWC/0qNE7JZ1hxHRNc9Mitjcbu2oiHteFgmnnKwL/WDGdAUBGhUmq43RgWP1Lg1Ty2MDMWnzkmS1+kuUJgkclDFCWRmibjbcAVJ6PHfRO7IR3YLAVIc5OSbloAfOztzJo2iU6lAq5vjToPGvmFQ6VzGvD62figODID8l/ukMPCcfq8bFTg6pPIrYEP8DgbCHHMBGngtbYxwGwc6DLEOceRON3Jz168DYjQMxRf5fBwwSnFwgYGJnAfV5lnSNwwkroFjiReWHIz7wwRwj2wvNWi5ocxmJ8yn9XzfPveqpTRle0ZSpL2yJpH8SeHmuMIHTQcy0sevCuyLyuodubrweRFXTpzQhiRif9nXdAaRKWfsVwmnWWu85EymxMQo= #DOCKER_PASS
  - secure: QL7LGf7ZRC6488qxYE+v6HHfF/xjrZ2rqGjZ1OCcqHRlKi/R2j1+JM8otnxKKXBVyoyGUEGNruI8NtourtnQwrTysRPaBeuJE1cYNX6aWogBp2Trkkzw24JLtlfN8mSKPgLqX4//mjPegjF+5RpnQaW4/L4QfFt0/RoBYxGlwtJY/0qRDgboi33a5ze33ikFlpPxJKu6rfM5FDccxyvbLyiyt3tfYoSIPvZRsgci+QQGAzwv49jWz0Pr3Wl3Ga2YuW3xd27awPzmlHZcSzHMH+ga0ieuezkg7p1L/LQyS+pmzYud/EAlgJU3YDG099UKODqJLYJbuYJQraMccjN7YjHM6viiEabGeEFREoAdki9Lh2yt9DWs3QsYOAG+2G01S/RrVcicv3l2w6V49o0Zfr8sDszH/yOYNjOEYUGoT4HNhDl8rSTMu8vikF/RJJ2UoxUh2nSU/YZOjDmo5g4oa+JR8pWHtMNTsxPEr4yWzv73vK3NAWwskdU8XDl9r2+EbAhruPzf3Jwur3u6zo3gaCj4H6VdDSVNXBSuMC9vI2UiNtV8Uh1//CUInVwZdF0VRNi1PFDxo87DqXBPRnHQd0ERw7Wew82AMjH/Pk1avhr/Wxq/6DhqFaYklhQQWt4e1VTV1hgnNg4RozmBXR1TFJsxCqvV5kMYODnGAqqaQaY= #GH_TOKEN (Greenkeeper)
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dargmuesli/jonas-thelemann.de
before_install:
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
script: docker build -f dockerfile -t $REPO:$COMMIT .
after_script:
- greenkeeper-lockfile-upload
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  provider: releases
  api_key:
    secure: KHbFXU3EVO65Q149886jqRlnsOR7WbtX5WNRpj6XZs9w0/3Iw/IcQHFC9POKN0f5P5d3C6j9M8/MGjqP6DLRibDuzNLM+zCL/EArk1PX6jqzTmaGsbbsn6vMBRF8FjtQ8bjiYqAa6xvxbfEcWmtSJ49KLxcKMNfii2pgxMWjXum63dV7szr8EED0fpWoZiTf5d4TK0wLm/ROWtLEwPIR91EhsV+i6fyE1+maRZXB7QYrpOH2/FeRnuBAoUQfa2jNSY/yz7TL6atV46SdgvlFwAiq1f17mUlQpCC/0wsmhRKrmSM2XIsY/4aO1e0oJBUL/NCmQdKLIFUbgRJWJ8joTaDo5txUEl7os8Sfr7/qlNEUhgXg1e1RhukCvjk1wCOsPsN8iL6BCKGaR4AbH0+AUSGPyHbkxV4ToGXmW19qIX+kFNmVJu117wMz8pIsovt/heQctdCS7lbRh+ZXqVWAult/ntfXNbdAK04aJ7BusCEJFCCN/TpUusvbKAidZNXM46AirC9wbs7mPfAG84N5/YZRvqJK9pCw/zPrINgbkWj4f85t+Z5NiZRA2J7/QmektWstRs0ZpeuOVlnUVbbrQR+JqAryvIVvasaTLXWDaAMLizJYv4U8IH607wxjEQU5XzF0+WUL+9LX1WpA+VvCKBP/gRTK9KNAgwT1m62zGvA=
  file: dist/jonas-thelemann.de.zip
  skip_cleanup: true
  on:
    tags: true
    repo: Dargmuesli/jonas-thelemann.de
notifications:
  email:
    on_success: change
    on_failure: change
